name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/strumenta'
  DOCKER_VERSION: '243.21565'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build documentation using Writerside Docker builder
        run: |
          mkdir -p artifacts
          docker run --rm \
            -v "$PWD:/project" \
            -w /project \
            jetbrains/writerside-builder:${DOCKER_VERSION} \
            /writerside/build.sh --input . --output artifacts

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: writerside-docs
          path: artifacts/

      - name: Push built documentation as a package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create a release version tag
          RELEASE_TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "Release tag: $RELEASE_TAG"

          # Package the built artifact and upload it to GitHub Packages
          mkdir -p ./package
